testaes-decrypt: testaes-decrypt.c aes-decrypt.c
	gcc -o testaes-decrypt testaes-decrypt.c aes-decrypt.c -I .

testaes-encrypt: testaes-encrypt.c aes-encrypt.c
	gcc -o testaes-encrypt testaes-encrypt.c aes-encrypt.c -I .

all: testaes-decrypt testaes-encrypt
